const ICONS: Record<string, string> = {
  vehicles: '🚗', cars: '🚙', 'motorcycles-scooters': '🏍️', 'buses-microbuses': '🚌',
  'vehicle-parts-accessories': '🔧', 'trucks-trailers': '🚛', 'boats-watercraft': '🚤',
  'heavy-equipment': '🏗️', 'car-audio-electronics': '🔊', 'other-vehicles': '🚲',
  property: '🏠', 'houses-apartments-sale': '🏡', 'houses-apartments-rent': '🏢',
  'short-let-vacation-rentals': '🌴', 'land-plots': '🗺️', 'commercial-property-sale': '🏬',
  'commercial-property-rent': '🏪', 'new-builds': '🏗️', 'rooms-rent-shared': '🚪',
  'parking-storage': '🅿️',
  'phones-tablets': '📱', 'mobile-phones': '📲', tablets: '📟', 'smart-watches': '⌚',
  'phone-tablet-accessories': '🎧', 'phone-parts-repair-tools': '🔩',
  electronics: '💻', 'laptops-computers': '💻', 'tv-video-equipment': '📺',
  'video-game-consoles': '🎮', 'audio-music-equipment': '🎵', 'cameras-photography': '📷',
  'computer-accessories': '🖱️', 'printers-scanners': '🖨️', 'networking-modems': '🌐',
  'monitors-displays': '🖥️', 'computer-components': '⚙️', 'home-audio-speakers': '🔊',
  'car-electronics': '📻', 'security-surveillance': '📹', 'smart-home-devices': '🏠',
  'other-electronics': '🔌',
  'home-furniture-appliances': '🛋️', furniture: '🪑', lighting: '💡',
  'storage-organization': '📦', 'home-accessories-decor': '🖼️', 'kitchen-dining': '🍽️',
  'bedding-bath': '🛏️', 'major-appliances': '🧊', 'small-kitchen-appliances': '☕',
  'garden-outdoor': '🌿',
  fashion: '👗', 'womens-fashion': '👩', 'womens-clothing': '👚', 'womens-shoes': '👠',
  'womens-bags': '👜', 'womens-jewelry': '💍', 'womens-watches': '⌚',
  'womens-clothing-accessories': '🧣', 'womens-wedding-wear': '👰',
  'mens-fashion': '👔', 'mens-clothing': '👕', 'mens-shoes': '👞', 'mens-bags': '💼',
  'mens-jewelry': '💎', 'mens-watches': '⌚', 'mens-clothing-accessories': '🧢',
  'mens-wedding-wear': '🤵', 'baby-kids-fashion': '👶', 'childrens-clothing': '👕',
  'childrens-shoes': '👟', 'babies-kids-accessories': '🧸',
  'beauty-personal-care': '💄', 'hair-beauty': '💇', 'face-care-skin-care': '🧴',
  'oral-care': '🪥', 'body-care-bath': '🛁', 'makeup-cosmetics': '💄',
  'fragrance-deodorants': '🧴', 'nail-care': '💅', 'mens-grooming': '🪒',
  'beauty-tools-accessories': '🔧', 'wellness-relaxation': '🧘',   'other-beauty-personal-care': '🧖',
  'medicine-health': '💊', 'vitamins-supplements': '💊', 'herbal-remedies': '🌿',
  'first-aid-emergency': '🚑', 'medical-equipment-devices': '🩺', 'pharmacy-prescription': '💊',
  'fitness-nutrition': '🥗', 'sexual-wellness': '❤️', 'eye-care-vision': '👁️',
  'hearing-audiology': '🦻', 'orthopedic-mobility-aids': '🦯',
  'maternity-baby-health': '🤱', 'other-health-supplies': '🏥',
  services: '🛠️', 'building-trades-services': '🔨', 'car-services-automotive': '🔧',
  'computer-it-services': '🖥️', 'repair-services': '🔩', 'cleaning-domestic-services': '🧹',
  'health-beauty-services': '💆', 'photography-videography': '📸',
  'event-planning-catering': '🎉', 'tutoring-education': '📚', 'legal-services': '⚖️',
  'financial-accounting-services': '💰', 'marketing-advertising': '📢',
  'web-mobile-development': '💻', 'writing-translation': '✍️', 'logistics-delivery': '📦',
  'moving-relocation': '🚚', 'pet-services': '🐾', 'travel-tours': '🧳',
  'fitness-personal-training': '🏋️', 'music-entertainment': '🎵',
  'printing-stationery': '🖨️', 'design-creative': '🎨', 'security-services': '🛡️',
  consulting: '💡', 'other-services': '📋',
  'repair-construction': '🔧', 'electrical-equipment': '⚡', generators: '🔋',
  'solar-renewable-energy': '☀️', 'inverters-backup-batteries': '🔋',
  'switches-sockets-distribution': '🔌', 'stabilizers-voltage-protection': '⚡',
  'welding-machinery-construction': '🔩', 'industrial-electrical-automation': '🏭',
  'electronic-components-sensors': '🔬', 'cables-wires': '🔌',
  'building-materials-supplies': '🧱', 'plumbing-water-systems': '🚰',
  'electrical-hand-tools': '🔧', 'construction-heavy-machinery': '🏗️',
  'paints-coatings': '🎨', 'doors-windows': '🚪', 'flooring-tiles': '🏠',
  'roofing-gutters': '🏠', 'fencing-gates': '🏡', 'bathroom-sanitary-ware': '🚿',
  'security-alarm-systems': '🔔', 'other-repair-construction': '🔨',
  'commercial-equipment-tools': '🏭', 'medical-equipment-supplies': '🏥',
  'safety-equipment-protective-gear': '🦺', 'manufacturing-equipment': '🏭',
  'manufacturing-materials-supplies': '📦', 'office-furniture-equipment': '🪑',
  'restaurant-catering-equipment': '🍳', 'retail-shop-equipment': '🛒',
  'agriculture-farm-equipment': '🚜', 'printing-packaging-equipment': '📦',
  'laboratory-equipment': '🔬', 'other-commercial-equipment': '⚙️',
  'leisure-activities': '🎯', 'sports-equipment-gear': '⚽', 'bicycles-cycling': '🚲',
  'musical-instruments-gear': '🎸', 'personal-mobility': '🛴', 'massagers-relaxation': '💆',
  'camping-hiking': '🏕️', 'fitness-exercise-equipment': '🏋️', 'books-magazines': '📚',
  'art-collectibles': '🎨', 'other-leisure-activities': '🎪',
  'babies-kids': '👶', 'toys-games': '🧸', 'childrens-furniture': '🛏️',
  'baby-gear-accessories': '👶', 'diapers-baby-care': '🍼', 'feeding-nursing': '🍼',
  'strollers-car-seats': '👶', 'nursery-furniture-decor': '🛏️', 'educational-toys-books': '📚',
  'other-babies-kids': '🧒',
  'food-agriculture-farming': '🌾', 'food-beverages': '🍽️',
  'farm-animals-livestock': '🐄', 'seeds-fertilizers-feeds': '🌱',
  'farm-machinery-equipment': '🚜', 'fresh-produce-groceries': '🥬',
  'animals-pets': '🐾', 'dogs-puppies': '🐕', 'cats-kittens': '🐈',
  'fish-aquariums': '🐟', birds: '🐦', 'pet-accessories-supplies': '🦴',
  'pet-food-treats': '🍖', 'other-pets': '🐹',
  jobs: '💼', 'accounting-finance-jobs': '💰', 'advertising-marketing-jobs': '📢',
  'arts-entertainment-jobs': '🎭', 'childcare-babysitting-jobs': '👶',
  'cleaning-domestic-jobs': '🧹', 'construction-trades-jobs': '🔨',
  'customer-service-jobs': '📞', 'education-training-jobs': '📚',
  'engineering-technical-jobs': '⚙️', 'food-service-hospitality-jobs': '🍳',
  'healthcare-nursing-jobs': '🏥', 'hr-recruitment-jobs': '👥',
  'it-software-development-jobs': '💻', 'legal-jobs': '⚖️',
  'logistics-transportation-jobs': '🚚', 'manufacturing-production-jobs': '🏭',
  'marketing-pr-jobs': '📣', 'media-journalism-jobs': '📰',
  'ngo-social-work-jobs': '🤝', 'office-admin-jobs': '📋',
  'real-estate-property-jobs': '🏠', 'retail-sales-jobs': '🛒',
  'security-military-jobs': '🛡️', 'telecommunications-jobs': '📡',
  'training-internship': '🎓', 'transport-driving-jobs': '🚗',
  'travel-tourism-jobs': '🧳', 'other-jobs': '📋',
  'seeking-work-cvs': '📄', 'accounting-finance-cvs': '💰', 'advertising-marketing-cvs': '📢',
  'arts-entertainment-cvs': '🎭', 'childcare-babysitting-cvs': '👶',
  'cleaning-domestic-cvs': '🧹', 'construction-trades-cvs': '🔨',
  'customer-service-cvs': '📞', 'education-training-cvs': '📚',
  'engineering-technical-cvs': '⚙️', 'food-service-hospitality-cvs': '🍳',
  'healthcare-nursing-cvs': '🏥', 'hr-recruitment-cvs': '👥',
  'it-software-development-cvs': '💻', 'legal-cvs': '⚖️',
  'logistics-transportation-cvs': '🚚', 'manufacturing-production-cvs': '🏭',
  'marketing-pr-cvs': '📣', 'media-journalism-cvs': '📰',
  'ngo-social-work-cvs': '🤝', 'office-admin-cvs': '📋',
  'real-estate-property-cvs': '🏠', 'retail-sales-cvs': '🛒',
  'security-military-cvs': '🛡️', 'telecommunications-cvs': '📡',
  'training-internship-cvs': '🎓', 'transport-driving-cvs': '🚗',
  'travel-tourism-cvs': '🧳', 'other-cvs': '📋',
};

const FALLBACK_BY_KEYWORD: [RegExp, string][] = [
  [/car|vehicle|auto/i, '🚗'], [/phone|mobile|smartphone/i, '📱'],
  [/computer|laptop|pc|tech|electronic/i, '💻'], [/home|furniture|house/i, '🏠'],
  [/cloth|fashion|wear|apparel/i, '👗'], [/beauty|cosmetic|makeup|skin|hair/i, '💄'],
  [/food|grocer|agric|farm|fresh/i, '🌾'], [/pet|animal|dog|cat/i, '🐾'],
  [/job|work|career|employment/i, '💼'], [/cv|resume|seeking/i, '📄'],
  [/service|repair|maintenance/i, '🛠️'], [/sport|fitness|leisure|game|toy/i, '🎯'],
  [/baby|kid|children|toddler/i, '👶'],   [/medical|health|wellness|medicine|pharmacy|hospital/i, '🏥'],
  [/commercial|equipment|industrial/i, '🏭'], [/property|land|apartment|rent/i, '🏠'],
  [/accessor|jewelry|watch|bag/i, '🛍️'], [/shoe|footwear/i, '👞'],
  [/book|magazine|read/i, '📚'], [/music|instrument/i, '🎵'],
  [/camera|photo|video/i, '📷'], [/tool|construction|build/i, '🔧'],
  [/part|repair/i, '🔩'], [/other/i, '📋'],
];

export function categoryIcon(slug: string, name?: string): string {
  if (ICONS[slug]) return ICONS[slug];
  if (name) {
    for (const [pattern, icon] of FALLBACK_BY_KEYWORD) {
      if (pattern.test(name)) return icon;
    }
  }
  return '🛍️';
}
